# Generated by Django 5.2.2 on 2025-06-17 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userbranch',
            name='is_active',
        ),
        migrations.AddField(
            model_name='user',
            name='branches',
            field=models.ManyToManyField(related_name='users', through='users.UserBranch', to='common.branch'),
        ),
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(related_name='users', through='users.UserRole', to='common.role'),
        ),
    ]
