# Generated by Django 5.2.2 on 2025-07-01 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('password', models.TextField(max_length=300)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
