# Generated by Django 5.2.2 on 2025-06-16 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('controller', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenant',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='cashback',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='created_on',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='on_trial',
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='paid_until',
        ),
    ]
